version: '3.8'

services:
  # Main application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: handlowiec-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    env_file:
      - .env.local
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    networks:
      - handlowiec-network
    restart: unless-stopped

  # Redis for caching (optional for MVP but good for production)
  redis:
    image: redis:7-alpine
    container_name: handlowiec-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - handlowiec-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Nginx reverse proxy (for production-like setup)
  nginx:
    image: nginx:alpine
    container_name: handlowiec-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - handlowiec-network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  handlowiec-network:
    driver: bridge 